
version: '2'
# Named volumes
volumes:
  # MySQL Data
  patterns-mysql-data:
    driver: local
services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: patterns-mysql
    volumes:
      - patterns-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=patterns
      - MYSQL_DATABASE=patterns
      - MYSQL_USER=patterns
      - MYSQL_PASSWORD=patterns


  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.1-nginx
    container_name: patterns-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql

